routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();
Route::middleware('auth')->group(function () {
Route::resource('/license', 'LicenseController');
Route::post('license/key','LicenseController@exp_date')->name('license.exp_date');
Route::post('key/update','LicenseController@key_save')->name('license.key_save');
Route::post('key_update_save','LicenseController@key_update')->name('license.key_update');
});

app/License.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class License extends Model
{
      protected $guarded=[];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password','fname','lname','nOfOrganization','street','city','phone',
        
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LicenseController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\User;
use Carbon\Carbon;

class LicenseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('license.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('license.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $id=Auth::user()->id;
        if($user=User::where('id',$id)->first()){           
            $user->user_id=$request->user_id;
            $user->save();
        } 
        $userDetails=User::where('id',$id)->first();
        return view('license.index', compact('userDetails'))->with('value', 1);                  
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }



      public function exp_date(Request $request)
    {

     $key= mt_getrandmax();
     $currentDateTime = Carbon::now();
     $newDateTime = Carbon::now()->addMonth($request->exp_date);
     //return $newDateTime;

       $id=Auth::user()->id;
        if($user=User::where('id',$id)->first()){           
            $user->exp_date=$newDateTime;
            $user->save();
        } 
        $userDetails=User::where('id',$id)->first();
        return view('license.date', compact('userDetails','key'))->with('value', 1);

    }


      public function key_save(Request $request)
    {
        $id=Auth::user()->id;
        if($user=User::where('id',$id)->first()){           
            $user->license_key=$request->licenseKey;
            $user->save();
        } 
        $userDetails=User::where('id',$id)->first();
        return view('license.updateKey', compact('userDetails','key'))->with('value', 1);       
    }


      public function key_update(Request $request)
    {
      // return $request;
        $id=Auth::user()->id;
        if($user=User::where('id',$id)->first()){           
            $user->license_key=$request->licenseKey;
            $user->save();
        } 
        $userDetails=User::where('id',$id)->first();
        return view('license.index', compact('userDetails','key'));       
    }




}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create License') }}</div>

                <div class="card-body" style="background-color: #9cc16d">
                    <form method="POST" action="{{ route('license.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="user_id" class="col-md-4 col-form-label text-md-right">{{ __('Client ID') }}</label>

                            <div class="col-md-6">
                                <input id="user_id" type="user_id" class="form-control @error('user_id') is-invalid @enderror" name="user_id" value="{{ old('user_id') }}" required autocomplete="user_id" autofocus>

                                @error('user_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License Key') }}</label>

                            <div class="col-md-6">
                                <input id="" type="licenseKey" class="form-control " name="licenseKey" >

                            </div>
                        </div>


                          <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right"></label>

                            <div class="col-md-6">
                                <button style="width: 328px" type="submit" class="btn btn-info">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>




                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License For') }}</label>

                            <div class="col-md-2">
                              
                          </div>
                            <div class="col-md-2">
                               <div class="form-group">
                              <select class="form-control" id="sel1" style="width:112px;">
                                <option>3</option>
                                <option>6</option>
                                <option>12</option>
                                
                              </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                          <p>Months</p>    
                        </div>
                        </div>



                        <div class="form-group row mb-0">
                            <div class="col-md-4 offset-md-8">
                                <button type="submit" class=".btn-default">
                                    {{ __('Create Key') }}
                                   
                                </button><br>
                                 {{ __('Return to Login Page') }}

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Perky Rabbit Corporation</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Perky Rabbit Corporation Ltd.
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->fname }} {{ Auth::user()->lname }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/license/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create License') }}</div>

                <div class="card-body" style="background-color: #9cc16d">
                    <form method="POST" action="{{ route('license.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="user_id" class="col-md-4 col-form-label text-md-right">{{ __('Client ID') }}</label>

                            <div class="col-md-6">
                                <input id="user_id" type="user_id" class="form-control @error('user_id') is-invalid @enderror" name="user_id" value="{{ old('user_id') }}" required autocomplete="user_id" autofocus>

                                @error('user_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License Key') }}</label>

                            <div class="col-md-6">
                                <input id="" type="licenseKey" class="form-control " name="licenseKey" >

                            </div>
                        </div>


                          <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right"></label>

                            <div class="col-md-6">
                                <button style="width: 328px" type="submit" class="btn btn-info">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>




                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License For') }}</label>

                            <div class="col-md-2">
                              
                          </div>
                            <div class="col-md-2">
                               <div class="form-group">
                              <select class="form-control" id="sel1" style="width:112px;">
                                <option>3</option>
                                <option>6</option>
                                <option>12</option>
                                
                              </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                          <p>Months</p>    
                        </div>
                        </div>



                        <div class="form-group row mb-0">
                            <div class="col-md-4 offset-md-8">
                                <button type="submit" class=".btn-default">
                                    {{ __('Create Key') }}
                                   
                                </button><br>
                                 {{ __('Return to Login Page') }}

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/license/date.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">

                </div>

                <div class="card-body" style="background-color: #9cc16d">
                    <form method="POST" action="{{ route('license.key_save') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="clientID" class="col-md-4 col-form-label text-md-right">{{ __('Client ID') }}</label>

                            <div class="col-md-6">
                                <input id="clientID" type="clientID" class="form-control @error('clientID') is-invalid @enderror" name="clientID" value="{{$userDetails->user_id}}" required autocomplete="clientID" autofocus disabled="">

                                @error('clientID')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License Key') }}</label>

                            <div class="col-md-6">
                                <input id="licenseKey" type="licenseKey" class="form-control @error('licenseKey') is-invalid @enderror" value="{{$key}}" name="licenseKey"  >

                                @error('licenseKey')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                          <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right"></label>

                            <div class="col-md-6">
                                <button onclick="myFunction()" style="width: 328px" type="submit" class="btn btn-info">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>




                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License For') }}</label>

                            <div class="col-md-2">
                              
                          </div>
                            <div class="col-md-2">
                               <div class="form-group">
                              <select class="form-control" id="sel1" name="exp_date" style="width:112px;" disabled>
                                <option value="3">3</option>
                                <option value="6">6</option>
                                <option value="12">12</option>
                                
                              </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                          <p>Months</p>    
                        </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-4 offset-md-8">
                                <button type="submit" class=".btn-default">
                                    {{ __('Create Key') }}
                                   
                                </button><br>
                                 {{ __('Return to Login Page') }}

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function myFunction() {
  alert("Congratulations!! Your License Has Been Activated. It will work till {{$userDetails->exp_date}} ");
}
</script>
@endsection

resources/views/license/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">

			     <div class="container">
					  <h2>Create License</h2>
					  <table class="table table-bordered">
					    <tbody>
					      <tr>
					        <td>First Name</td>
					        <td>{{$userDetails->fname}}</td> 
					      </tr>
					      <tr>
					        <td>Last Name</td>
					         <td>{{$userDetails->lname}}</td> 
					      </tr>
					      <tr>
					        <td>Name of Organization</td>
					         <td>{{$userDetails->nOfOrganization}}</td> 
					      </tr>
					      <tr>
					        <td>Street</td>
					         <td>{{$userDetails->street}}</td> 
					      </tr>
					      <tr>
					        <td>City</td>
					         <td>{{$userDetails->city}}</td> 
					      </tr>
					       <tr>
					        <td>Phone</td>
					         <td>{{$userDetails->phone}}</td> 
					      </tr>
					       <tr>
					        <td>Email</td>
					        <td>{{$userDetails->email}}</td> 
					      </tr>
					       <tr>
					        <td>License Key</td>
					        <td>{{$userDetails->license_key}}</td> 
					      </tr>
					    </tbody>
					  </table>
					</div>

                </div>

                <div class="card-body" style="background-color: #9cc16d">
                    <form method="POST" action="{{ route('license.exp_date') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="clientID" class="col-md-4 col-form-label text-md-right">{{ __('Client ID') }}</label>

                            <div class="col-md-6">
                                <input id="clientID" type="clientID" class="form-control @error('clientID') is-invalid @enderror" name="clientID" value="{{$userDetails->user_id}}" required autocomplete="clientID" autofocus disabled="">

                                @error('clientID')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License Key') }}</label>

                            <div class="col-md-6">
                                <input id="licenseKey" type="licenseKey" class="form-control @error('licenseKey') is-invalid @enderror" name="licenseKey" >

                                @error('licenseKey')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                          <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right"></label>

                            <div class="col-md-6">
                                <button style="width: 328px" type="submit" class="btn btn-info">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>




                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License For') }}</label>

                            <div class="col-md-2">
                              
                          </div>
                            <div class="col-md-2">
                               <div class="form-group">
                              <select class="form-control" id="sel1" name="exp_date" style="width:112px;">
                                <option value="3">3</option>
                                <option value="6">6</option>
                                <option value="12">12</option>
                                
                              </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                          <p>Months</p>    
                        </div>
                        </div>



                        <div class="form-group row mb-0">
                            <div class="col-md-4 offset-md-8">
                                <button type="submit" class=".btn-default">
                                    {{ __('Create Key') }}
                                   
                                </button><br>
                                 {{ __('Return to Login Page') }}

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/license/updateKey.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
               

                <div class="card-body" style="background-color: #9cc16d">
                    <h3>Enter License Key </h3><br>
                    <form method="POST" action="{{ route('license.key_update') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right">{{ __('License Key') }}</label>

                            <div class="col-md-6">
                                <input id="licenseKey" type="licenseKey" class="form-control @error('licenseKey') is-invalid @enderror" value="" name="licenseKey"  >

                                @error('licenseKey')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                          <div class="form-group row">
                            <label for="licenseKey" class="col-md-4 col-form-label text-md-right"></label>

                            <div class="col-md-6">
                                <button onclick="myFunction()" style="width: 328px" type="submit" class="btn btn-info">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>



                        <div class="form-group row mb-0">
                            <div class="col-md-4 offset-md-8">
                                <button type="submit" class=".btn-default">
                                    {{ __('Create Key') }}
                                   
                                </button><br>
                                 {{ __('Return to Login Page') }}

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection